source 'https://rubygems.org'

gem 'credentials_manager', '0.16.0', :git => 'https://github.com/fastlane/fastlane.git', :tag => 'credentials_manager/0.16.0'
gem 'fastlane', '~> 2.23' 
gem 'cocoapods', '1.0.1'
