project 'HelloRest/HelloRest.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

def testing_pods
  pod 'Quick'
  pod 'Nimble'
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end 

def networking_pods
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'ReactiveCocoa', '~> 4.1'
end 

def layout_pods
  pod 'PureLayout'
end

target 'HelloRest' do
  networking_pods
  layout_pods
end

target 'HelloRestSpecs' do
  testing_pods
end
