project 'HelloRest/HelloRest.xcodeproj'

platform :ios, '9.3'

use_frameworks!

pod 'SwiftyJSON'
pod 'Alamofire'
pod 'ReactiveCocoa', '~> 4.1'
pod 'PureLayout'

target 'HelloRest' do

end

target 'HelloRestSpecs' do
  pod 'Quick'
  pod 'Nimble'
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end
